### ISSUE TITLE
For your durable object alarm are you calculating ts_less_than correctly?

### ISSUE THREAD

**Issue by OultimoCoder** [ianapiron/durable-limiter#5]
I maybe completely misunderstanding this so forgive me if this is the case, but say we take:

`ts_less_than: Math.floor(now / 1000 / parseInt(interval)) - parseInt(interval) * 2`

This is `number of intervals - the interval seconds * 2`.

Shouldn't you be doing  `number of intervals -2 intervals` aka:

`Math.floor(now / 1000 / parseInt(interval)) - 2`

**Comment by honzabit** [comment]
hey @OultimoCoder! The interval here represents the bucket's time length depending on the configuration of the rate-limit rule.

For `fixed` algo, you need 1 active bucket at a time, so:
```ts_less_than: Math.floor(now / 1000 / parseInt(interval)) - parseInt(interval)```
deletes buckets older than the `current` which is the only one in use.

For `sliding` window algo, you actually need 2 buckets to calculate the rate of requests, so:
```ts_less_than: Math.floor(now / 1000 / parseInt(interval)) - parseInt(interval) * 2```
this code, actually deletes buckets older than the last 2 ones which are considered `current`.

I hope that makes sense.

**Comment by OultimoCoder** [comment]
Let me just confirm a few things.

Now()/1000

Is equal to the Unix timestamp in seconds.

Now()/1000/parseInt(interval)

Give us just the current interval and how many intervals there have ever
been.

E.g. if timestamp in seconds was 1000 and interval was 10 seconds there
have been 100 intervals and our current interval is number 100.

Now for the sliding window algorithm if we takeaway 20 seconds (aka
parseInt*2) from 100 we get 90 which is actually 10 intervals ago.

I still don't understand why we just dont takeaway 2 to get 98 as that
seems more accurate to me.

**Comment by OultimoCoder** [comment]
I'm on my phone apologies for unformatted reply I'll edit it at work.

**Comment by honzabit** [comment]
I think you are right! The fact that the cleanup code has no tests leads up to this :)

I have no idea why I put the ` / interval` in there. Let me have a second look in a while, and I will get back to you about this.

Thanks for pointing this out 👍

**Comment by OultimoCoder** [comment]
I have written a couple of simple integration tests for the alarm which I
can share. It's how I found this :)

**Comment by honzabit** [comment]
Sure, please do! 👍 

I pushed the updated code, let me know if you have any issues.

**Comment by OultimoCoder** [comment]
Sorry I still think the fix was wrong. Your key stores the timestamp as:

`const currentWindow = Math.floor(Date.now() / 1000 / config.interval)`

So with a timestamp of 1000 and interval of 10 it will be stored as 100.

Say the alarm ran in the same period, your fix was:

`const ts_less_than = Math.floor(now / 1000) - parseInt(interval)`

Which would be 1000 - 10 which is the same issue we had last time :)

Current window shouldn't be divided by the interval to match but you use it in other calculations so I am inclinded to keep it the same as:

`const currentWindow = Math.floor(Date.now() / 1000 / config.interval)`

And instead change the alarm to do:

`const ts_less_than = Math.floor(now / 1000 / parseInt(interval)) - 1` for fixed

and 

`const ts_less_than = Math.floor(now / 1000 / parseInt(interval)) - 2` for sliding

**Comment by honzabit** [comment]
Heh, that makes sense, that's why the division was there 🙄. 

Sorry but I'm currently committed to another project that uses this code internally, but as I said I still haven't found the time to write tests for this alarm. Without the tests any changes I make are "in good faith" 😄

I will try to write some tests for the alarm and push the fix in the next few hours hopefully.

Thanks again for your input!

**Comment by honzabit** [comment]
Heh, that makes sense and shows why the division was there in the first place.

I'm using this code in another project but I still haven't gotten to the point to write the tests, and the tests published here are really basic, from the time I pushed the initial code.

I will try to find some time to write tests for the alarm and eventually push a fix for this 🙄 .

Thank you again for your input!

**Comment by OultimoCoder** [comment]
```
import httpStatus from 'http-status';
import MockDate from 'mockdate'
import dayjs from 'dayjs'
import isSameOrBefore from 'dayjs/plugin/isSameOrBefore'

dayjs.extend(isSameOrBefore)

const env = getMiniflareBindings()
const key = '127.0.0.1'
const id = env.RATE_LIMITER.idFromName(key)
const fakeDomain = 'http://iamaratelimiter.com'

describe('Alarm', () => {
    let storage: DurableObjectStorage

    beforeEach(async () => {
      storage = await getMiniflareDurableObjectStorage(id);
      MockDate.reset()
    });

    test('should expire key after 2 intervals have passed', async () => {
      const config = {
        scope: '/v1/auth/send-verification-email',
        key,
        limit: 1,
        interval: 60
      }
      const rateLimiter = env.RATE_LIMITER.get(id)
      const currentWindow = Math.floor(dayjs().unix() / config.interval);
      const storageKey = `${config.scope}|${config.key.toString()}|${config.limit}|` +
        `${config.interval}|${currentWindow}`

      const res = await rateLimiter.fetch(
        new Request(fakeDomain, {
          method: 'POST',
          body: JSON.stringify(config)
        })
      )
      expect(res.status).toBe(httpStatus.OK)
      const values = await storage.list()
      expect(values.size).toBe(1)
      expect(values.get(storageKey)).toBe(1)

      MockDate.set(dayjs().add(config.interval * 3, 'seconds').toDate())
      await flushMiniflareDurableObjectAlarms()
      const values2 = await storage.list()
      expect(values2.size).toBe(0)
    });

    test('should not expire key if within 2 intervals', async () => {
      const config = {
        scope: '/v1/auth/send-verification-email',
        key,
        limit: 1,
        interval: 60
      }
      const rateLimiter = env.RATE_LIMITER.get(id)
      const currentWindow = Math.floor(dayjs().unix() / config.interval);
      const storageKey = `${config.scope}|${config.key.toString()}|${config.limit}|` +
        `${config.interval}|${currentWindow}`

      const res = await rateLimiter.fetch(
        new Request(fakeDomain, {
          method: 'POST',
          body: JSON.stringify(config)
        })
      )
      expect(res.status).toBe(httpStatus.OK)
      const values = await storage.list()
      expect(values.size).toBe(1)
      expect(values.get(storageKey)).toBe(1)

      MockDate.set(dayjs().add(config.interval * 1.5, 'seconds').toDate())
      await flushMiniflareDurableObjectAlarms()
      const values2 = await storage.list()
      expect(values2.size).toBe(1)
      expect(values2.get(storageKey)).toBe(1)
    });

    test('should expire keys that are more than 2 intervals old and keep the others', async () => {
      const config = {
        scope: '/v1/auth/send-verification-email',
        key,
        limit: 1,
        interval: 60
      }
      const rateLimiter = env.RATE_LIMITER.get(id)

      const currentWindow = Math.floor(dayjs().unix() / config.interval);
      const storageKey = `${config.scope}|${config.key.toString()}|${config.limit}|` +
        `${config.interval}|${currentWindow}`

      const res = await rateLimiter.fetch(
        new Request(fakeDomain, {
          method: 'POST',
          body: JSON.stringify(config)
        })
      )
      expect(res.status).toBe(httpStatus.OK)

      const expiredWindow = Math.floor(dayjs().unix() / config.interval - 3) ;
      const expiredStorageKey = `${config.scope}|${config.key.toString()}|${config.limit}|` +
        `${config.interval}|${expiredWindow}`

      await storage.put(expiredStorageKey, 45)

      const expiredWindow2 = Math.floor(dayjs().unix() / config.interval - 7) ;
      const expiredStorageKey2 = `${config.scope}|${config.key.toString()}|${config.limit}|` +
        `${config.interval}|${expiredWindow2}`

      await storage.put(expiredStorageKey2, 33)

      const expiredWindow3 = Math.floor(dayjs().unix() / config.interval - 4) ;
      const expiredStorageKey3 = `${config.scope}|${config.key.toString()}|${config.limit}|` +
        `${config.interval}|${expiredWindow3}`

      await storage.put(expiredStorageKey3, 12)

      const window2 = Math.floor(dayjs().unix() / config.interval - 1.5)
      const storageKey2 = `${config.scope}|${config.key.toString()}|${config.limit}|` +
        `${config.interval}|${window2}`

      await storage.put(storageKey2, 12)

      const values = await storage.list()
      expect(values.size).toBe(5)

      await flushMiniflareDurableObjectAlarms()

      const values2 = await storage.list()
      expect(values2.size).toBe(2)
      expect(values2.get(expiredStorageKey)).toBeUndefined()
      expect(values2.get(expiredStorageKey2)).toBeUndefined()
      expect(values2.get(expiredStorageKey3)).toBeUndefined()
      expect(values2.get(storageKey)).toBe(1)
      expect(values2.get(storageKey2)).toBe(12)
    });
  });
```

Here are some super simple tests I wrote. I edited the rateLimiter object slightly for mine so there is no type (I am just using sliding) but feel free to ignore or use anything here.

**Comment by honzabit** [comment]
Super, thanks a lot! 👍  I will read them the first chance I get!

**Comment by honzabit** [comment]
Hey, I added 2 tests, one for each algo and changed the alarm code to work with buckets, not with timestamps (it really was a mixup there). Also changed a bit the naming of the variables inside the alarm to better reflect their usage (was using `ts` while it was referring was "bucket id"). 

Check it out and let me know. I will also try to add these tests to the main project I'm using the rate-limiter into. Thanks again!

**Comment by honzabit** [comment]
Closing this. Thanks again @OultimoCoder!
